#pragma once
#include "openGlObject.h"
#include <glad/glad.h>

namespace nico {
	/**
	 * @class FrameBuffer
	 * @brief allow to draw in a texture rather than on the screen
	 */
	class FrameBuffer : public GlObject
	{
	public:
		/**
		 * @brief create a frameBuffer and bind it
		 */
		FrameBuffer();
		/**
		 * @brief symply bindly the frameBuffer
		 * generally use it by calling glClear() before
		 * and you can change the size of the image generated by calling glViewPort()
		 */
		void bind();
		/**
		 * @brief unbind all the framebuffers
		 */
		void unbind();
		/**  
		 * \return true if the Frame Buffer is completed
		 */
		bool checkFrameBufferComplete();
 	};
}


